services:
    menu.menu_builder:
        class: Menu\MenuBuilder
        arguments:
            - '@knp_menu.factory'
            - '@security.context'
            - '@translator'

    navbar.main_menu:
        class: Knp\Menu\MenuItem
        factory_service: 'menu.menu_builder'
        factory_method: 'createMainMenu'
        tags:
            - { name: 'knp_menu.menu', alias: 'main' }
